### ISSUE TITLE
Releases haven't been updated in 6 years

### ISSUE THREAD

**Issue by cmdrscotty** [omf2097/openomf#384]
Granted I know this project is a work in progress and it can be compiled from the guy source, but strikes me as odd that the releases channel hasn't been updated since 2014.

**Comment by katajakasa** [comment]
Oh, there is nothing odd about it. It's simply that the developers are lazy :)

**Comment by cricri-pingouin** [comment]
The binaries page says:

There are unofficial windows and linux binaries available at http://katajakasa.fi/projects/openomf/packages/. These are updated every now and then, and may or may not work.

But the link is dead. I browsed the folders of http://katajakasa.fi/projects/openomf and couldn't find any binaries anywhere.

Lazy, ok, but 7 years without a build! I mean, surely developers have to build the binaries anyway to check things are working, so why not release it?
As for building ourselves, good luck. I once installed Visual Studio, and of about the half dozen VS projects I tried to compile, I managed to build none. Some projects don't have a makefile, and the ones that did generated errors. Libs are missing, pathes are wrong, wrong libraries versions, etc. I've since given up on trying to compile any Visual Studio projects myself, and in fact, I've uninstalled VS completely.

**Comment by katajakasa** [comment]
Binaries page ? I am unable to find that reference. Latest information should be in INSTALL.md document (linked on README.md): https://github.com/omf2097/openomf/blob/master/INSTALL.md

```
Latest experimental binaries

Latest experimental binaries for windows and debian (ubuntu) are available at https://buildbot.openomf.org/artifacts/ . These binaries may not always work correctly, but they will be following the git status very closely. So, if you with to test the latest features, this is for you!
```

As to building, Visual Studio is not supported in any case :) Build process is also described on the INSTALL.md document.

As to why there is no release -- it is a lot of work. When we make a release, we first have to roll the official builds and write release docs, and then when distros and people start testing it and re-releasing it, we get a bunch of issues to fix, which is then away from other development. And unfortunately, we don't currently have much time to even do normal development, let alone fix issues in a hurry. If you, or someone else reading this, is willing to either do the release work and issue fixes yourself (or optionally hire us to do this work), then we are certainly ready to discuss it on our discord channel (link on README.md doc). But otherwise, I'm sorry to say, this is how it is for now :(

**Comment by katajakasa** [comment]
Oh yeah, now I found the binaries page. You meant our website at openomf.org. Yeah, looks like nobody has remembered to do anything about that. I will go ahead and update it.

**Comment by cricri-pingouin** [comment]
Yes, I meant:
https://www.openomf.org/downloads/
Sorry, I could have been more specific!
Ah, ok, I didn't realise it was a lot of work. I only work with Turbo Delphi myself, and to test my app, I just build and run. Of course, my apps are not cross platforms, so obviously it makes it a lot easier for the IDE to make/build!

**Comment by katajakasa** [comment]
No problems.

I forgot to comment earlier, but the downloads page should be fully updated now (along with other updates).

Closing ticket as done.

**Comment by cricri-pingouin** [comment]
Awesome, just got the latest build and played a quick game!
