### ISSUE TITLE
AI problems with scrap/destruct.

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#434]
AI can do scrap/destruct moves. These seem to be broken, as AIs can freely move again after executing one of these, when they should return to the victory pose. Also, gargoyle scrap animation caused a segfault (not sure why).

**Comment by katajakasa** [comment]
No longer crashy after 4160dfbbac74efd73b75a823c235628e31b44a4f

**Comment by katajakasa** [comment]
Never mind, got this to reoccur with Gargoyles destruction move.

**Comment by gdeda** [comment]
I believe this is related (or mostly related) to how scrap/destruction is handled.
I'm trying to explain better: when I use Nova and attempt a scrap, sometimes I miss the destruction and another move (punch, earthquake smash...) can happen, like there is a little "space" between the "you win" event and the end of the scrap/destruction.
It's quite funny because I get again the "you win", the winning pose and can execute a scrap/destruction again,
Much likely AI is better in exploiting these moments.

I believe #290 could play some role on this behaviour.
